feature-fix-cors
Programowanie-Zespolowe-PAJDA/Backend pull request #17
Opened 2024-01-09 15:05 UTC by ThePapiok

2024-01-11 11:51 UTC, kacper-cf requested changes
I would expect it to be tested 🤔

2024-01-11 16:02 UTC, ThePapiok commented
> I would expect it to be tested 🤔

I tested it with Adam, only the production frontend can communicate with the production backend, for example local frontend can't communicate with the production backend. Is that what you meant?

2024-01-12 08:33 UTC, kacper-cf approved these changes

2024-01-12 18:28 UTC, Makolin0 approved these changes
approved, works

2024-01-12 18:31 UTC, merged